#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { z } from "zod/mini";

import {
  NAMESPACES,
  REGISTERED_COMMANDS,
  ROLE_NAMES,
  RUNTIME_CONTRACT_VERSION,
  SUPPORTED_OMP_VERSION,
  TaskDispatchSchema,
  canonicalAgentName,
} from "../../.omp/extensions/pi-oven-runtime/runtime-contract";

export const generatedArtifacts = [
  "docs/generated/runtime-contract.md",
  "docs/generated/task-dispatch.schema.json",
] as const;

export type GeneratedArtifact = (typeof generatedArtifacts)[number];

function runtimeContractMarkdown(): string {
  const roleRows = ROLE_NAMES.map(
    (role) => `| \`${role}\` | \`${canonicalAgentName(role)}\` |`,
  ).join("\n");
  const commands = REGISTERED_COMMANDS.map((command) => `- \`${command}\``).join("\n");

  return `# Generated Runtime Contract

> Generated by \`bun run contract:generate\`. Do not edit by hand.

This reference is derived from \`.omp/extensions/pi-oven-runtime/runtime-contract.ts\`.

Contract version: \`${RUNTIME_CONTRACT_VERSION}\`

Supported OMP package: \`@oh-my-pi/pi-coding-agent@${SUPPORTED_OMP_VERSION}\`

## Namespaces

| Surface | Namespace |
|---|---|
| Runtime agents | \`${NAMESPACES.agent}:<role>\` |
| Workflow skills | \`${NAMESPACES.skill}:<skill>\` |
| Slash commands | \`${NAMESPACES.command}:<command>\` |
| Install identity | \`${NAMESPACES.install}\` |

## Runtime agent roster (${ROLE_NAMES.length})

| Role | Canonical dispatch name |
|---|---|
${roleRows}

## Registered slash commands

${commands}

## Canonical task dispatch

The universal authored subset uses one canonical agent and one or more literal task items. Optional runtime fields are \`context\`, \`schema\`, and \`isolated\`. Every item requires \`id\`, \`description\`, and \`assignment\`; \`blockedBy\` may reference only IDs in the same call and must form a DAG.

<!-- pi-oven-contract:task-example -->
\`\`\`ts
task({
  agent: "pov:executor",
  tasks: [
    {
      id: "implement",
      description: "Implement the scoped change",
      assignment: "Implement the approved change and run its focused tests.",
    },
  ],
});
\`\`\`

The machine-readable schema is in [\`task-dispatch.schema.json\`](./task-dispatch.schema.json).
`;
}

function taskDispatchJsonSchema(): string {
  const schema = z.toJSONSchema(TaskDispatchSchema, {
    target: "draft-2020-12",
  }) as Record<string, unknown>;
  return `${JSON.stringify(
    {
      $id: "https://github.com/kimzerokim/pi-oven/contracts/task-dispatch.schema.json",
      title: "pi-oven canonical OMP task dispatch",
      description: "Generated from the pi-oven RuntimeContract TaskDispatchSchema.",
      ...schema,
    },
    null,
    2,
  )}\n`;
}

export function renderGeneratedArtifacts(): Record<GeneratedArtifact, string> {
  return {
    "docs/generated/runtime-contract.md": runtimeContractMarkdown(),
    "docs/generated/task-dispatch.schema.json": taskDispatchJsonSchema(),
  };
}

export function generateRuntimeContractFiles(root = resolve(import.meta.dir, "../..")): void {
  for (const [file, content] of Object.entries(renderGeneratedArtifacts())) {
    const path = join(root, file);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}

if (import.meta.main) generateRuntimeContractFiles();
